# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: create test folder
        run: mkdir /home/vitali/projects/mckc-dwrr/test/actions-runner/test_passed
        
      - name: copy file
        run: cp src/bff/client.js /home/vitali/projects/mckc-dwrr/test/actions-runner/test_passed


